data:
  patch_size: 9
  mode: labeled_only
seed: 7
split:
  mode: image
  train_ratio: 1
dataloader_train:
  batch_size: 4096
  num_workers: 4
  shuffle: True
dataloader_val:
  batch_size: 4096
  num_workers: 4
  shuffle: False
autoencoder:
  n_input_channels: 8
  embedding_size: 8
  model_type: conv
  conv_channels: [48, 96, 192]
  activation: relu
  dropout_rate: 0.0
  denoising: false
  noise_std: 0.0
optimizer:
  name: adamw
  lr: 0.000005
  weight_decay: 0.00001
trainer:
  max_epochs: 20
  log_every_n_steps: 50
  limit_val_batches: 0
  num_sanity_val_steps: 0
output:
  dirpath: '../results/exp_028'
    # you should use your name and your experiment number here
wandb:
  project: 'lab2-autoencoder'
  name: 'exp_028_finetune'
    # you should use your name and your experiment number here
init_checkpoint: '../results/exp_028/exp_028_pretrain.pt'
    # you should use your name and your pretraining experiment number here
