autoencoder:
  activation: relu
  conv_channels:
  - 48
  - 96
  - 192
  denoising: true
  dropout_rate: 0.05
  embedding_size: 8
  model_type: conv
  n_input_channels: 8
  noise_std: 0.05
data:
  mode: labeled_only
  patch_size: 9
dataloader_train:
  batch_size: 4096
  num_workers: 4
  shuffle: true
dataloader_val:
  batch_size: 4096
  num_workers: 4
  shuffle: false
init_checkpoint: ../results/exp_040/exp_040_pretrain.pt
optimizer:
  lr: 5.0e-06
  name: adamw
  weight_decay: 1.0e-05
output:
  dirpath: ../results/exp_040
seed: 7
split:
  mode: image
  train_ratio: 1
trainer:
  limit_val_batches: 0
  log_every_n_steps: 50
  max_epochs: 20
  num_sanity_val_steps: 0
wandb:
  name: exp_040_finetune
  project: lab2-autoencoder
