autoencoder:
  activation: relu
  conv_channels:
  - 48
  - 96
  - 192
  denoising: true
  dropout_rate: 0.0
  embedding_size: 8
  model_type: conv
  n_input_channels: 8
  noise_std: 0.05
data:
  mode: unlabeled_only
  patch_size: 9
dataloader_train:
  batch_size: 4096
  num_workers: 4
  shuffle: true
dataloader_val:
  batch_size: 4096
  num_workers: 4
  shuffle: false
optimizer:
  lr: 0.0005
  name: adamw
  weight_decay: 1.0e-05
output:
  dirpath: ../results/exp_039
seed: 7
split:
  mode: image
  test_ratio: 0.1
  train_ratio: 0.8
  val_ratio: 0.1
trainer:
  log_every_n_steps: 500
  max_epochs: 100
wandb:
  name: exp_039_pretrain
  project: lab2-autoencoder
