name: env_214_test
channels:
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - pyyaml
  - tqdm
  - lightgbm
  - statsmodels
  - xgboost
  - pip:
      - torch
      - lightning
      - wandb
